### ISSUE TITLE
QUESTION: Possibility to start Kodi application on recipe launch implemented.

### ISSUE THREAD

**Issue by 4nderss** [alxbauer/neeo-driver-kodi#1]
Does this work if SDK is installed on another machine? I have a raspberry pi dedicated for Neeo SDKS but would like this feature since HTPC sometimes restarts and this would be better then autostart kodi on boot since KODI can crash etc.

**Comment by alxbauer** [comment]
Yes. I've also a dedicated linux machine to run those services.
